language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - hhvm

install: composer update

script: vendor/bin/phpunit --coverage-text

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
